apiVersion: v1
kind: Service
metadata:
  name: angular-service
  labels:
    app: openapi
spec:
  type: NodePort
  ports: 
    - nodePort: 30080
      port: 80
      targetPort: 80
      protocol: TCP
  selector: 
    app: openapi
    type: frontend