apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: openapi
spec:
  type: NodePort
  ports: 
    - nodePort: 30800
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector: 
    app: openapi
    type: backend