apiVersion: v1
kind: Service
metadata:
  name: node-port-service
  labels:
    app: test
spec:
  type: loadBalancer
  ports: 
    - nodePort: 32000
      port: 80
      targetPort: 80
  selector: 
    app: test
    type: front-end