apiVersion: v1
kind: Service
metadata:
  name: node-port-service
  labels:
    app: openapi
spec:
  type: NodePort
  ports: 
    - nodePort: 32000
      port: 80
      targetPort: 80
  selector: 
    app: openapi
    type: front-end